@startuml 订单状态图
预订: 订单创建\n订单详情\n客户信息\n金额
待付款: 作业完毕\n商家工作结束
关闭: 交易非正常结束

[*] --> 预订

预订 --> 待付款: 生产\n加工\n包装
预订 --> 关闭: 订单取消

待付款 -> 关闭: 可能有亏损
待付款 --> 付款后: 付款

关闭 --> [*]

state 付款后 {
    待发货: 付款完毕\n联系快递\n用户自提
    待确认: 快递已经到达\n客户已经收货\n等待客户确认
    退货: 货物返还
    退款: 撤销订单\n金额返还
    完成: 交易打成

    [*] --> 待发货
    待发货 -> 待确认: 快递送达\n用户提货
    待发货 --> 退款: 发货前退款

    待确认 -> 完成: 超时限\n可自动完成
    待确认 --> 退货: 客户不满意
    待确认 --> 退款: 退款不退货\n需协商

    退货 --> 退款: 收到货物后
    退款 -> [*]

    完成 --> 退款: 退款不退货\n需协商
    完成 --> 退货: 先退货再退款
    完成 -> [*]
}
付款后 -> [*]
@enduml
